### ISSUE TITLE
❓Installation instructions for pytorch-geometric

### ISSUE THREAD

**Issue by goxeq** [mir-group/nequip#103]
In the Installation section in https://github.com/mir-group/nequip/blob/main/README.md,
there is a link to installation instructions of pytorch-geometric (https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html), which points to the instructions for the current version and not the 1.7.2, which is required by nequip. 

I suggest you consider changing the link to the instructions for the version 1.7.2 at  https://pytorch-geometric.readthedocs.io/en/1.7.2/notes/installation.html

**Comment by Linux-cpp-lisp** [comment]
thanks for pointing this out @goxeq !
