### ISSUE TITLE
lammps Installation problem❓ [QUESTION]

### ISSUE THREAD

**Issue by deleep225** [mir-group/nequip#151]
I am able install nequip, lammps and torch separately.
when i try to patch and reinstall the lammps i got the following error.
how to solve it ?

CMake Error in CMakeLists.txt:
  Target "lammps" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "MKL_INCLUDE_DIR-NOTFOUND"

CMake Error in CMakeLists.txt:
  Target "lammps" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "MKL_INCLUDE_DIR-NOTFOUND"

CMake Error in CMakeLists.txt:
  Imported target "torch" includes non-existent path

    "MKL_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in CMakeLists.txt:
  Imported target "torch" includes non-existent path

    "MKL_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by simonbatzner** [comment]
Closing this since Deleep in personal communication reported this was not an issue anymore.

**Comment by chenruduan** [comment]
Hi @deleep225 @simonbatzner, Could any of you weigh in about the reasons/solutions for this? I think I am having the exact same issue on Mac. It seems it misses some MKL libs but I am not sure. Thanks!

**Comment by deleep225** [comment]
Hi Chenru,
you need to install mkl libraries.
After installing my libraries were installed in the path below.
-DMKL_INCLUDE_DIR=/usr/include/

command for installation
cmake ../cmake -DCMAKE_PREFIX_PATH=`python -c 'import
torch;print(torch.utils.cmake_prefix_path)'` -DMKL_INCLUDE_DIR=/usr/include/

**Comment by simonbatzner** [comment]
Hi @chenruduan, yes, just like @deleep225 said, you need to install the MKL libraries, on my system it was 

```
conda install mkl-include
```

and then set it in the cmake command, so first get the dir where `mkl.h` lives: 

```
find $HOME -name  mkl.h
```

and then set: 

```
cmake ../cmake -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` -DMKL_INCLUDE_DIR=path/to/that/dir/
```

Let me know if that works.

**Comment by chenruduan** [comment]
@simonbatzner @deleep225 Thank you both! With that, I got the configuration step passed!
