### ISSUE TITLE
wrong ValueError text

### ISSUE THREAD

**Issue by IHumonen** [mir-group/nequip#262]
https://github.com/mir-group/nequip/blob/41d6b2d5a83a9c3d8f9803a802e9b44e7f8fe65f/nequip/train/trainer.py#L1180

This line should have n_val instead of n_train in the error text

**Comment by Linux-cpp-lisp** [comment]
Hi @IHumonen ,

Thanks for catching this... fixed in https://github.com/mir-group/nequip/commit/bb2a1204c972cca9daed467a56236dc54aaf677b
