### ISSUE TITLE
❓ [QUESTION] Newton pair when running lammps

### ISSUE THREAD

**Issue by jic198** [mir-group/nequip#280]
Hello,

I am not sure if it's the right place to ask this question. But I am getting the following error when running lammps with Nequip trained ML potential:
`ERROR: Pair style NEQUIP requires newton pair off (src/pair_nequip.cpp:108)`
What do you think could be the problem? I am using lammps-29Sep21 and nequip.0.5.5

Thanks!

**Comment by Linux-cpp-lisp** [comment]
Hi @jic198 ,

You just need to add
```
newton off
```
to your LAMMPS script, as the error says.

**Comment by jic198** [comment]
Ah. Thank you so much! It's working now.
