### ISSUE TITLE
🌟 [FEATURE] Support for newer PyTorch

### ISSUE THREAD

**Issue by tgmaxson** [mir-group/nequip#294]
**Is your feature request related to a problem? Please describe.**
Is there a plan to support newer versions of PyTorch in the near or far future?  Currently installing PyTorch from Conda restricts the python version since there is no PyTorch=1.11 for Python>=3.10 as far as I can tell.

**Comment by Linux-cpp-lisp** [comment]
Hi @tgmaxson ,

It isn't marked on `main` yet since I was being conservative, but 1.13 should work fine.  Avoid 1.12.
