### ISSUE TITLE
🐛 [BUG]  Does not work with RTX 4080 GPU

### ISSUE THREAD

**Issue by vasalx** [mir-group/nequip#315]
**Describe the bug**
Does not work with RTX 4080 GPU

**Expected behavior**
Package works with latest NVIDIA GPUs, including RTX 4080

**Additional context**
PyTorch and CUDA of the supported by the package versions are not compatible with the latest NVIDIA GPUs. Is it possible (planned) to make NequIP compatible with the latest PyTorch and CUDA?

**Comment by vasalx** [comment]
Hi @simonbatzner, thanks for getting back so fast.

As described in https://github.com/pytorch/pytorch/issues/91973,  stable PyTorch 1.13.x with CUDA 11.6 or 11.7 should be good. Not sure if this is relevant, but cuFFT works only with CUDA 11.8 which requires a nightly build of PyTorch.

This is not exclusive to 4080, though. All higher end 40xx NVIDIA GPUs seem to be affected, and possibly even 3090.

**Comment by Linux-cpp-lisp** [comment]
@vasalx we are affected by upstream issues that exist in 1.13 (but not in 1.11) that _may_ affect you if you use PyTorch!=1.11 (see https://github.com/mir-group/nequip/discussions/311), but besides these PyTorch bugs we do support 1.13.  What problem are you having, exactly?

**Comment by vasalx** [comment]
Hi, @Linux-cpp-lisp! How do I make it work with the latest then? When I try to update existing conda env, I start to get CUDA errors (do not have them handy, but will try to replicate if needed). In new env with preinstalled latest PyTorch and CUDA, trying to install NequIP degrades those to the requirements of the package (PT 1.11).

**Comment by vasalx** [comment]
@Linux-cpp-lisp, never mind. I see that it is possible on the `develop` branch. Sorry for troubling you!

**Comment by Linux-cpp-lisp** [comment]
No worries, thanks for your interest in our code @vasalx !
