### ISSUE TITLE
Is it possible to train on xyz format data with multiple molecules❓ [QUESTION]

### ISSUE THREAD

**Issue by utkarshp1161** [mir-group/nequip#351]
for example: H20 and CH4
4
H     0.0     0.0     0.0
O     0.9572  0.0     0.0
H     1.2072  0.0     0.0

5
C     0.0     0.0     0.0
H     0.627  -0.627  -0.627
H    -0.627   0.627  -0.627
H     0.627   0.627   0.627
H    -0.627  -0.627   0.627

I tried and I am getting following error:
  File "/nequip/nequip/nn/embedding/_one_hot.py", line 41, in forward
    one_hot = torch.nn.functional.one_hot(
RuntimeError: CUDA error: device-side assert triggered

**Comment by Eipgen** [comment]
you can use extended xyz file

**Comment by Linux-cpp-lisp** [comment]
Thanks @Eipgen for answering this!

**Comment by DQM520** [comment]
> you can use extended xyz file like this
> 
> ```
> 2
> Properties=species:S:1:pos:R:3:forces:R:3 energy=-13486.77734375 pbc='F F F'
> C  11.480999946594238 1.6349999904632568 1.2079999446868896 3.3895702362060547 -0.8061511516571045 1.0440574884414673
> O  11.880999565124512 1.5490000247955322 2.385999917984009 -1.0153744220733643 0.45024925470352173 -1.1317808628082275
> 4
> Properties=species:S:1:pos:R:3:forces:R:3 energy=-13486.77734375 pbc='F F F'
> H  16.160999298095703 -2.3320000171661377 7.361000061035156 1.2726770639419556 0.4869202673435211 0.26308372616767883
> C  16.42799949645996 -2.74399995803833 6.388000011444092 -0.6890028119087219 -0.4337579905986786 1.2225674390792847
> H  17.1560001373291 -3.553999900817871 6.4070000648498535 0.23268871009349823 0.009330789558589458 0.4573668837547302
> H  16.733999252319336 -2.0299999713897705 5.622000217437744 -0.005286495666950941 0.3279768228530884 0.3452637195587158
> ```
I don't know how to get the extended xyz file like this, could you help me with the question?[How to prepare xyz format data(extended xyz file) for training? · mir-group/nequip · Discussion #463 (github.com)](https://github.com/mir-group/nequip/discussions/463) Thank you so much!

**Comment by DQM520** [comment]
> Thanks @Eipgen for answering this!

Could you help me with the question?[How to prepare xyz format data(extended xyz file) for training? · mir-group/nequip · Discussion #463 (github.com)](https://github.com/mir-group/nequip/discussions/463) Thank you so much!
