### ISSUE TITLE
The use of nequip command

### ISSUE THREAD

**Issue by isseitoida** [mir-group/nequip#363]
pip install nequip

I was able to run this command locally to complete the installation, but the nequip command used to run the test computation afterwards is not recognized.
If you know how to solve this problem, please let me know. Thank you in advance.

**Comment by cw-tan** [comment]
Sorry for the delayed response. The following works for me locally using the recently released `nequip-0.6.0` (https://github.com/mir-group/nequip/discussions/430) in a fresh conda environment.
```
conda create -n nequip python=3.11
conda activate nequip
pip install torch==1.13
pip install nequip
```
Creating an empty directory with `minimal.yaml` ([this one](https://github.com/mir-group/nequip/blob/main/configs/minimal.yaml)) in it and calling
```
nequip-train minimal.yaml
```
begins training. Let us know if your problem persists.
