### ISSUE TITLE
Default Units in the outputs of training

### ISSUE THREAD

**Issue by tkacju** [mir-group/nequip#417]
Good afternoon, I want to ask what are the default Units in outcome of the error of the training. I am using exyz dataset. In Google colab tutorial I have seen that you had kcal/mol or eV, is it possible that I have also these units? 
Best, 
Juraj Tkáč

**Comment by Linux-cpp-lisp** [comment]
Hi @tkacju ,

`nequip` reports errors and trains models in whatever units the training data is provided in.  Please note, however, that the training data **must** be internally self-consistent in its units, both in the sense that the units must be the same and must be consistent (i.e. if energies are in eV and distances in Angstrom, forces must be in eV / A).
