### ISSUE TITLE
🐛 [BUG] `InvalidVersion` in v0.6.0

### ISSUE THREAD

**Issue by janosh** [mir-group/nequip#431]
**Describe the bug**

v0.6.0 is raising

```py
packaging.version.InvalidVersion: Invalid version: ''
```

in [atomate2 CI](https://github.com/materialsproject/atomate2/actions/runs/9045715286/job/24855741891)

<details><summary>stack trace</summary>

```py
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/atomate2/forcefields/md.py", line 333, in calculator
    return ase_calculator(self.force_field_name, **self.calculator_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/atomate2/forcefields/utils.py", line 439, in ase_calculator
    calculator = NequIPCalculator.from_deployed_model(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nequip/ase/nequip_calculator.py", line 62, in from_deployed_model
    model, metadata = nequip.scripts.deploy.load_deployed_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nequip/scripts/deploy.py", line 131, in load_deployed_model
    assert packaging.version.parse(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```
</details> 

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - python version: 3.9

**Additional context**

was fine before v0.6.0

**Comment by janosh** [comment]
presumably caused by this line

https://github.com/mir-group/nequip/blob/3db69640fabb684db1e13ec56826c3cb6586fafc/nequip/utils/versions.py#L10-L15

**Comment by Linux-cpp-lisp** [comment]
Hi @janosh ,

Thanks for the bug report---I should be able to commit a fix for this, but likely the easiest fix at your end would just be to re-deploy the trained model you are using in the CI using 0.6.0 to get a file that isn't affected by the possible past bug I believe to be triggering this.

I didn't realize `nequip` was integrated in atomate2, out of curiosity what is it used for there?

**Comment by janosh** [comment]
thanks for the fix @Linux-cpp-lisp!

`nequip` was added to `atomate2` by @jonathanschmidt1. i'm not an active nequip user myself (yet) but looks like `atomate2` integration covers [MD](https://github.com/materialsproject/atomate2/blob/50ae3c05daa5d6e2deaeda4c37a4277e7b7ac4f5/src/atomate2/forcefields/md.py#L375), [relax](https://github.com/materialsproject/atomate2/blob/50ae3c05daa5d6e2deaeda4c37a4277e7b7ac4f5/src/atomate2/forcefields/jobs.py#L302) and [static](https://github.com/materialsproject/atomate2/blob/50ae3c05daa5d6e2deaeda4c37a4277e7b7ac4f5/src/atomate2/forcefields/jobs.py#L343) jobs
