### ISSUE TITLE
[Duplicate BUG] Google Colab link isn't accessible

### ISSUE THREAD

**Issue by mattbrownrigg** [mir-group/nequip#437]
### Discussed in https://github.com/mir-group/nequip/discussions/436

<div type='discussions-op-text'>

<sup>Originally posted by **mayaniyogi** June 19, 2024</sup>
In the tutorial section, there's a link to a Google Colab notebook, but when I try to click the link, it says Access Denied. However I see that 3 weeks ago it was possible to open it, so I'm wondering if I need to change something on my end or if it's geniunely an access issue. Any advice would be appreciated!
<img width="763" alt="Screenshot 2024-06-19 at 16 10 14" src="https://github.com/mir-group/nequip/assets/76263542/c7e15741-0446-4c55-bdd8-8b348e300519">
</div>

**Comment by mattbrownrigg** [comment]
Duplicate Bug to #435

**Comment by ChengQIAN93** [comment]
Yes, the Google Colab link still not work. Is there a PDF manual available?

**Comment by cw-tan** [comment]
Hi @mattbrownrigg and @ChengQIAN93,

Thank you for your interest in NequIP and apologies for the inconvenience. Unfortunately, the Google account hosting the Colab tutorial expired and we haven't been able to recover the notebook so far. For learning how to use `nequip`, I'd recommend reading through `nequip/configs/example.yaml` [here](https://github.com/mir-group/nequip/blob/main/configs/example.yaml) and `nequip/configs/full.yaml` [here](https://github.com/mir-group/nequip/blob/main/configs/full.yaml), and trying to train models with those config files.
