### ISSUE TITLE
❓ [QUESTION] pytorch version requirement

### ISSUE THREAD

**Issue by skasamatsu** [mir-group/nequip#459]
There was a commit a couple of months ago regarding the pytorch version requirement;
https://github.com/mir-group/nequip/commit/5db1bd733201dc8f64ea5309ae76a8d43e024214

This doesn't allow use of pytorch 1.11.0+cu113, for example.
Is this the intended behavior?

**Comment by Linux-cpp-lisp** [comment]
Hi @skasamatsu ,

It should allow it... is it throwing an error for you?

The intention was to exclude PyTorch 1.12, on which we observed some severe bugs.

**Comment by skasamatsu** [comment]
It is throwing an error as follows:

> Traceback (most recent call last):
  File "/home/kasamatsu/.pyenv/versions/miniconda3-latest/envs/nequip/bin/nequip-train", line 5, in <module>
    from nequip.scripts.train import main
  File "/home/kasamatsu/.pyenv/versions/miniconda3-latest/envs/nequip/lib/python3.10/site-packages/nequip/__init__.py", line 15, in <module>
    torch_version >= packaging.version.parse("1.13")
AssertionError: NequIP supports PyTorch 1.11.* or 1.13.* or later, but 1.11.0+cu113 found

**Comment by Linux-cpp-lisp** [comment]
Hm.  We've been updating these checks anyway, so good to know this failure mode, but in the meantime feel free to just comment out the offending lines.  1.11.0+cu113 should work well.
