### ISSUE TITLE
❓ [QUESTION] Auto-set `r_max` to `float`?

### ISSUE THREAD

**Issue by kavanase** [mir-group/nequip#462]
When resuming jobs with `wandb`, in the reloaded config it sets my original `r_max=5.0` to `r_max=5` (i.e. an `int`).
This then causes the new job to re-process the dataset, as the hash is different and so it thinks the dataset is different when it is not. This is the only difference in `params.yaml`.

This could possibly be solved by enforcing `r_max` as always being a float? 

I guess this issue might also just be circumvented by the dataset revamps that @cw-tan has been working on

**Comment by cw-tan** [comment]
Yes -- this shouldn't be a problem if you use the new stuff on the `develop` branch.
