### ISSUE TITLE
TypeError when reading ASE dataset

### ISSUE THREAD

**Issue by kkly1995** [mir-group/nequip#88]
**Describe the bug**
Using an ASE dataset for `configs/minimal.yaml` instead of npz results in the following:
```
Loaded data: Batch(atomic_numbers=[21000], batch=[21000], cell=[1000, 3, 3], edge_cell_shift=[220186, 3], edge_index=[2, 220186], pbc=[1000, 3], pos=[21000, 3], ptr=[1001])
Successfully loaded the data set of type ASEDataset(1000)...
Traceback (most recent call last):
  File "/home/kkly2/anaconda3/envs/nequip/bin/nequip-train", line 8, in <module>
    sys.exit(main())
  File "/home/kkly2/anaconda3/envs/nequip/lib/python3.8/site-packages/nequip/scripts/train.py", line 40, in main
    fresh_start(parse_command_line(args))
  File "/home/kkly2/anaconda3/envs/nequip/lib/python3.8/site-packages/nequip/scripts/train.py", line 148, in fresh_start
    stats = trainer.dataset_train.statistics(
  File "/home/kkly2/anaconda3/envs/nequip/lib/python3.8/site-packages/nequip/data/dataset.py", line 328, in statistics
    elif len(arr) == self.data.num_graphs:
TypeError: object of type 'NoneType' has no len()
```

**To Reproduce**
I just took `configs/minimal.yaml` and modified just the data part:
```
$ diff minimal.yaml ~/nequip/configs/minimal.yaml
15,16c15,16
< dataset: ase
< dataset_file_name: ../MD17/aspirin_ccsd-train.xyz
---
> dataset: aspirin
> dataset_file_name: benchmark_data/aspirin_ccsd-train.npz
```
where `aspirin_ccsd-train.xyz` is from [here](http://quantum-machine.org/gdml/#datasets) (I assume the .npz is the same dataset?).

**Expected behavior**
As is, `configs/minimal.yaml` works for me without any errors, so I expected the same here when using ASE.

**Environment (please complete the following information):**
 - OS: Fedora 25
 - python version 3.8.3
 - python environment (commands are given for python interpreter):
   - nequip version 0.3.3
   - e3nn version 0.3.5
   - pytorch version 1.9.1

**Comment by Linux-cpp-lisp** [comment]
Hi @kkly1995 ,

This error usually comes up when a key that you try to compute statistics over — usually the energy or force when computing normalization constants — isn't in your dataset.

Can you run `python -m pdb nequip/nequip/scripts/train.py path/to/minimal.yaml` and run `p field` when it catches on this error?

Thanks.

**Comment by kkly1995** [comment]
It is true that I previously had a smaller dataset of the same name `subset.xyz` which had only 100 frames, which I since removed from this directory. The error reported above is after I replaced it with the larger dataset. I deleted `results/LaH/minimal` before rerunning but I also noticed there is `results/LaH/processed`. Just now I removed all these directories, it was able to successfully read all 500 frames. The error must be some artifact left over from when I ran a similar input, using the same directory but different `subset.xyz`.

**Comment by Linux-cpp-lisp** [comment]
Worth noting that this issue of cached processed versions of datasets getting out of sync with your dataset settings is resolved in the current beta version. However, that does _not_ include if you change the actual data file that is read from— we don't want to waste time reading it just to check if something has changed, so you _are_ responsible still for making sure that you reprocess if you change the _contents_ of a datafile.
